"""
ubuntu_tank_operator package.

Exposes constants, schemas, state machine, configuration, and lock management
for the MentorPi Tank operator authority and web control protocol.
"""

from .config import WebControlConfig
from .constants import (
    API_VERSION,
    BATTERY_FRESHNESS_MAX_AGE_SEC,
    CHALLENGE_INTERVAL_NS,
    CHALLENGE_INTERVAL_SEC,
    DEFAULT_OPERATOR_SOCKET_PATH,
    DEFAULT_WEB_ANGULAR_SPEED,
    DEFAULT_WEB_LINEAR_SPEED,
    DELIVERY_OBSERVATION_MAX_AGE_SEC,
    ENV_OPERATOR_LOCK_PATH,
    ENV_OPERATOR_SOCKET_PATH,
    FIRST_COMMAND_DEADLINE_NS,
    FIRST_COMMAND_DEADLINE_SEC,
    GUARD_STATE_FRESHNESS_MAX_AGE_SEC,
    IDLE_TIMEOUT_NS,
    IDLE_TIMEOUT_SEC,
    LEASE_CHECK_INTERVAL_NS,
    LEASE_CHECK_INTERVAL_SEC,
    LEASE_DURATION_NS,
    LEASE_DURATION_SEC,
    LOCK_LEVEL_DEPLOYMENT,
    LOCK_LEVEL_LIFECYCLE,
    LOCK_LEVEL_OPERATOR,
    LOCK_PATH_DEPLOYMENT,
    LOCK_PATH_LIFECYCLE,
    LOCK_PATH_OPERATOR,
    MAX_CONTINUOUS_HOLD_NS,
    MAX_CONTINUOUS_HOLD_SEC,
    MAX_IPC_MESSAGE_BYTES,
    MAX_LOG_BYTES_LIMIT,
    MAX_LOG_LINES_LIMIT,
    MAX_PERMISSIBLE_ANGULAR_SPEED,
    MAX_PERMISSIBLE_LINEAR_SPEED,
    MIN_SAFE_BATTERY_VOLTAGE,
    ODOM_FRESHNESS_MAX_AGE_SEC,
    PROTOCOL_VERSION,
    SCHEMA_VERSION,
    SUPPORTED_PROTOCOL_VERSIONS,
    TARGET_ZERO_SUBMISSION_DEADLINE_NS,
    TARGET_ZERO_SUBMISSION_DEADLINE_SEC,
)
from .enums import (
    ControllerServiceState,
    MotionDirection,
    OperatorState,
    WebControlErrorCode,
)
from .ipc_client import OperatorIpcClient
from .ipc_server import OperatorIpcServer, extract_peer_credentials
from .locks import (
    LockAcquisitionTimeoutError,
    LockHierarchy,
    LockOrderViolationError,
    execute_non_blocking_stop,
)
from .schemas import (
    Challenge,
    ChallengeResponse,
    ControlAcquireRequest,
    ControlAcquireResponse,
    ControlArmRequest,
    ControlArmResponse,
    ControllerOperationRequest,
    ControlReleaseRequest,
    ControlReleaseResponse,
    ControlStopRequest,
    ControlStopResponse,
    LoginRequest,
    LoginResponse,
    LogoutResponse,
    LogsRequest,
    LogsResponse,
    OperationStatusResponse,
    StatusResponse,
    TelemetrySnapshot,
    VersionResponse,
    WsClientFrame,
    WsServerFrame,
)
from .state_machine import OperatorStateMachine
from .agent_node import OperatorAgentNode

__all__ = [
    "API_VERSION",
    "BATTERY_FRESHNESS_MAX_AGE_SEC",
    "CHALLENGE_INTERVAL_NS",
    "CHALLENGE_INTERVAL_SEC",
    "DEFAULT_OPERATOR_SOCKET_PATH",
    "DEFAULT_WEB_ANGULAR_SPEED",
    "DEFAULT_WEB_LINEAR_SPEED",
    "DELIVERY_OBSERVATION_MAX_AGE_SEC",
    "ENV_OPERATOR_LOCK_PATH",
    "ENV_OPERATOR_SOCKET_PATH",
    "FIRST_COMMAND_DEADLINE_NS",
    "FIRST_COMMAND_DEADLINE_SEC",
    "GUARD_STATE_FRESHNESS_MAX_AGE_SEC",
    "IDLE_TIMEOUT_NS",
    "IDLE_TIMEOUT_SEC",
    "LEASE_CHECK_INTERVAL_NS",
    "LEASE_CHECK_INTERVAL_SEC",
    "LEASE_DURATION_NS",
    "LEASE_DURATION_SEC",
    "LOCK_LEVEL_DEPLOYMENT",
    "LOCK_LEVEL_LIFECYCLE",
    "LOCK_LEVEL_OPERATOR",
    "LOCK_PATH_DEPLOYMENT",
    "LOCK_PATH_LIFECYCLE",
    "LOCK_PATH_OPERATOR",
    "MAX_CONTINUOUS_HOLD_NS",
    "MAX_CONTINUOUS_HOLD_SEC",
    "MAX_IPC_MESSAGE_BYTES",
    "MAX_LOG_BYTES_LIMIT",
    "MAX_LOG_LINES_LIMIT",
    "MAX_PERMISSIBLE_ANGULAR_SPEED",
    "MAX_PERMISSIBLE_LINEAR_SPEED",
    "MIN_SAFE_BATTERY_VOLTAGE",
    "ODOM_FRESHNESS_MAX_AGE_SEC",
    "PROTOCOL_VERSION",
    "SCHEMA_VERSION",
    "SUPPORTED_PROTOCOL_VERSIONS",
    "TARGET_ZERO_SUBMISSION_DEADLINE_NS",
    "TARGET_ZERO_SUBMISSION_DEADLINE_SEC",
    "Challenge",
    "ChallengeResponse",
    "ControlAcquireRequest",
    "ControlAcquireResponse",
    "ControlArmRequest",
    "ControlArmResponse",
    "ControlReleaseRequest",
    "ControlReleaseResponse",
    "ControlStopRequest",
    "ControlStopResponse",
    "ControllerOperationRequest",
    "ControllerServiceState",
    "LockAcquisitionTimeoutError",
    "LockHierarchy",
    "LockOrderViolationError",
    "LoginRequest",
    "LoginResponse",
    "LogoutResponse",
    "LogsRequest",
    "LogsResponse",
    "MotionDirection",
    "OperationStatusResponse",
    "OperatorAgentNode",
    "OperatorIpcClient",
    "OperatorIpcServer",
    "OperatorState",
    "OperatorStateMachine",
    "StatusResponse",
    "TelemetrySnapshot",
    "VersionResponse",
    "WebControlConfig",
    "WebControlErrorCode",
    "WsClientFrame",
    "WsServerFrame",
    "execute_non_blocking_stop",
    "extract_peer_credentials",
]
